### ISSUE TITLE
Mark newly opened PR as wip

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/limbo-config#3]
The current situation is a bit messy.

A contributor needs to mark manually a PR by commenting ~wip or ~qa, but that's documented nowhere.

It would be good if limbo could mark a new PR as wip and posting a comment along the lines of "If you think this PR is ready, comment with ~qa"

EDIT: What I meant when I said `documented` was that a user has no way of knowing limbo's tricks when he's opening a PR.

**Comment by ryantheleach** [comment]
I'd be ok with this, but would rather it reply with the instructions, instead of assuming it's status.

**Comment by liach** [comment]
you are already able to mark it by starting the title with [wip]

**Comment by liach** [comment]
@ImMorpheus https://github.com/SpongePowered/limbo-config/blob/d098fa52d425e01db66ac740a8af2e5f00c2e990/include/github/apply.xml#L56-L64

**Comment by phit** [comment]
@liach which is also undocumented..

**Comment by liach** [comment]
@phit Where is the documentation? I never knew there was one.

**Comment by phit** [comment]
https://github.com/SpongePowered/limbo-config/wiki

but thats not what I meant, its more like how is a pr author gonna know about this. kashike is working on a automatic message for first time contributors telling them about the commands
